---
title: Jean Wojciechowski
timezone: America/Sao_Paulo
collections:
  projects:
    title: Projects
    output: true
    sort_by: position
  typefaces:
    title: Typefaces
    output: false
  uploads:
    title: Uploads
    output: true
  posts:
    title: Work In Progress
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
- scope:
    path: ''
    type: projects
  values:
    title: Title
    project_name: Name
    project_headline: Headline
    project_brief: Brief
    project_creative_field: Creative Field
    project_client: Client
    project_headline_homepage: 
    project_cover_image: 
    typeface: 
    layout: project
- scope:
    path: ''
    type: typefaces
  values:
    title: Typeface Name
    font_options: 
    homepage_type_tester:
      font_option: Option Name
      default_text: |-
        Text to show in
        Homepage
    project_page_type_testers:
    - font_option: Option Name
      default_text: |-
        Text to show in
        Project Page
    opentype_features:
    - 
email: woj.jean@gmail.com
description: Hi, my name is Jean Wojciechowski, I’m a Brazilian graphic designer with
  special interest in visual branding and type design.
baseurl: 
url: 
twitter_username: 
github_username: 
links:
  arena: https://www.are.na/jean-wojciechowski
  behance: https://www.behance.net/jeanwoj
  instagram: https://www.instagram.com/jean.woj/
  tumblr: https://jeanwojciechowski.tumblr.com/
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
exclude:
- tsconfig.json
- scripts.ts
- yarn.lock
- package.json
